/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalDatePicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalPicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/MusicPlayer`; params?: Router.UnknownInputParams; } | { pathname: `/pages/components/webviewFetcher`; params?: Router.UnknownInputParams; } | { pathname: `/services/extract`; params?: Router.UnknownInputParams; } | { pathname: `/services/rules`; params?: Router.UnknownInputParams; } | { pathname: `/services/webviewFetcher`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ModalDatePicker`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ModalPicker`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MusicPlayer`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/components/webviewFetcher`; params?: Router.UnknownOutputParams; } | { pathname: `/services/extract`; params?: Router.UnknownOutputParams; } | { pathname: `/services/rules`; params?: Router.UnknownOutputParams; } | { pathname: `/services/webviewFetcher`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ModalDatePicker${`?${string}` | `#${string}` | ''}` | `/components/ModalPicker${`?${string}` | `#${string}` | ''}` | `/components/MusicPlayer${`?${string}` | `#${string}` | ''}` | `/pages/components/webviewFetcher${`?${string}` | `#${string}` | ''}` | `/services/extract${`?${string}` | `#${string}` | ''}` | `/services/rules${`?${string}` | `#${string}` | ''}` | `/services/webviewFetcher${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalDatePicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalPicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/MusicPlayer`; params?: Router.UnknownInputParams; } | { pathname: `/pages/components/webviewFetcher`; params?: Router.UnknownInputParams; } | { pathname: `/services/extract`; params?: Router.UnknownInputParams; } | { pathname: `/services/rules`; params?: Router.UnknownInputParams; } | { pathname: `/services/webviewFetcher`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
